---
galaxy_info:
  role_name: ds-sudo
  author: DeadSwitch
  description: SUDO configuration
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
