---
galaxy_info:
  role_name: ds-ssh
  author: DeadSwitch
  description: OpenSSH server configuration
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
